"""esquema inicial: posts, curtidas e comentarios

Revision ID: c8aad232b73e
Revises: 
Create Date: 2026-09-26 11:16:31.671049
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'c8aad232b73e'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('universidade_id', sa.UUID(), nullable=False),
    sa.Column('autor_id', sa.UUID(), nullable=False),
    sa.Column('visibilidade', sa.Enum('publico', 'institucional', 'curso', name='visibilidade', schema='academic'), nullable=False),
    sa.Column('curso_id', sa.UUID(), nullable=True),
    sa.Column('conteudo', sa.String(length=2000), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('editado_em', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(visibilidade = 'curso') = (curso_id IS NOT NULL)", name=op.f('ck_posts_curso_id_exatamente_quando_restrito_a_curso')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_posts')),
    schema='academic'
    )
    op.create_index(op.f('ix_academic_posts_autor_id'), 'posts', ['autor_id'], unique=False, schema='academic')
    op.create_index(op.f('ix_academic_posts_curso_id'), 'posts', ['curso_id'], unique=False, schema='academic')
    op.create_index('ix_posts_universidade_criado_em', 'posts', ['universidade_id', 'criado_em'], unique=False, schema='academic')
    op.create_table('comentarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('autor_id', sa.UUID(), nullable=False),
    sa.Column('conteudo', sa.String(length=1000), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['academic.posts.id'], name=op.f('fk_comentarios_post_id_posts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comentarios')),
    schema='academic'
    )
    op.create_index(op.f('ix_academic_comentarios_autor_id'), 'comentarios', ['autor_id'], unique=False, schema='academic')
    op.create_index('ix_comentarios_post_criado_em', 'comentarios', ['post_id', 'criado_em'], unique=False, schema='academic')
    op.create_table('curtidas',
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['academic.posts.id'], name=op.f('fk_curtidas_post_id_posts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'usuario_id', name=op.f('pk_curtidas')),
    schema='academic'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('curtidas', schema='academic')
    op.drop_index('ix_comentarios_post_criado_em', table_name='comentarios', schema='academic')
    op.drop_index(op.f('ix_academic_comentarios_autor_id'), table_name='comentarios', schema='academic')
    op.drop_table('comentarios', schema='academic')
    op.drop_index('ix_posts_universidade_criado_em', table_name='posts', schema='academic')
    op.drop_index(op.f('ix_academic_posts_curso_id'), table_name='posts', schema='academic')
    op.drop_index(op.f('ix_academic_posts_autor_id'), table_name='posts', schema='academic')
    op.drop_table('posts', schema='academic')
    # ### end Alembic commands ###
