"""esquema inicial

Revision ID: 24b609a4e956
Revises: 
Create Date: 2026-09-23 18:53:58.798955
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '24b609a4e956'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credenciais',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('senha_hash', sa.String(length=200), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('senha_alterada_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credenciais')),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_credenciais_email'), 'credenciais', ['email'], unique=True, schema='auth')
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('credencial_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('familia_id', sa.UUID(), nullable=False),
    sa.Column('expira_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revogado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['credencial_id'], ['auth.credenciais.id'], name=op.f('fk_refresh_tokens_credencial_id_credenciais'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True, schema='auth')
    op.create_index('ix_refresh_tokens_credencial', 'refresh_tokens', ['credencial_id'], unique=False, schema='auth')
    op.create_index('ix_refresh_tokens_familia', 'refresh_tokens', ['familia_id'], unique=False, schema='auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_refresh_tokens_familia', table_name='refresh_tokens', schema='auth')
    op.drop_index('ix_refresh_tokens_credencial', table_name='refresh_tokens', schema='auth')
    op.drop_index(op.f('ix_auth_refresh_tokens_token_hash'), table_name='refresh_tokens', schema='auth')
    op.drop_table('refresh_tokens', schema='auth')
    op.drop_index(op.f('ix_auth_credenciais_email'), table_name='credenciais', schema='auth')
    op.drop_table('credenciais', schema='auth')
    # ### end Alembic commands ###
