"""esquema inicial: vagas e candidaturas

Revision ID: 1fcfcf6c5503
Revises: 
Create Date: 2026-09-28 20:12:17.939847
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '1fcfcf6c5503'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vagas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=120), nullable=False),
    sa.Column('descricao', sa.String(length=5000), nullable=False),
    sa.Column('tipo', sa.Enum('estagio', 'junior', 'trainee', name='tipo_de_vaga', schema='jobs'), nullable=False),
    sa.Column('modalidade', sa.Enum('presencial', 'hibrido', 'remoto', name='modalidade', schema='jobs'), nullable=False),
    sa.Column('local', sa.String(length=120), nullable=True),
    sa.Column('estado', sa.Enum('aberta', 'fechada', name='estado_da_vaga', schema='jobs'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('editado_em', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(modalidade = 'remoto') = (local IS NULL)", name=op.f('ck_vagas_local_exatamente_quando_nao_e_remoto')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vagas')),
    schema='jobs'
    )
    op.create_index('ix_vagas_empresa_criado_em', 'vagas', ['empresa_id', 'criado_em'], unique=False, schema='jobs')
    op.create_index('ix_vagas_estado_criado_em', 'vagas', ['estado', 'criado_em'], unique=False, schema='jobs')
    op.create_table('candidaturas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vaga_id', sa.UUID(), nullable=False),
    sa.Column('candidato_id', sa.UUID(), nullable=False),
    sa.Column('estado', sa.Enum('enviada', 'visualizada', name='estado_da_candidatura', schema='jobs'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('visualizada_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['vaga_id'], ['jobs.vagas.id'], name=op.f('fk_candidaturas_vaga_id_vagas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidaturas')),
    sa.UniqueConstraint('vaga_id', 'candidato_id', name='uq_candidaturas_vaga_candidato'),
    schema='jobs'
    )
    op.create_index('ix_candidaturas_candidato_criado_em', 'candidaturas', ['candidato_id', 'criado_em'], unique=False, schema='jobs')
    op.create_index('ix_candidaturas_vaga_criado_em', 'candidaturas', ['vaga_id', 'criado_em'], unique=False, schema='jobs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_candidaturas_vaga_criado_em', table_name='candidaturas', schema='jobs')
    op.drop_index('ix_candidaturas_candidato_criado_em', table_name='candidaturas', schema='jobs')
    op.drop_table('candidaturas', schema='jobs')
    op.drop_index('ix_vagas_estado_criado_em', table_name='vagas', schema='jobs')
    op.drop_index('ix_vagas_empresa_criado_em', table_name='vagas', schema='jobs')
    op.drop_table('vagas', schema='jobs')
    # ### end Alembic commands ###
