"""cnpj e estado de ativacao

Revision ID: 3510bd333ffc
Revises: ef394f3040de
Create Date: 2026-09-23 21:06:04.166287
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '3510bd333ffc'
down_revision: str | None = 'ef394f3040de'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('universidades', sa.Column('cnpj', sa.String(length=14), nullable=True), schema='user')
    op.create_index(op.f('ix_user_universidades_cnpj'), 'universidades', ['cnpj'], unique=True, schema='user')
    op.add_column('usuarios', sa.Column('cnpj', sa.String(length=14), nullable=True), schema='user')
    op.add_column('usuarios', sa.Column('ativada_em', sa.DateTime(timezone=True), nullable=True), schema='user')
    op.create_index(op.f('ix_user_usuarios_cnpj'), 'usuarios', ['cnpj'], unique=True, schema='user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_usuarios_cnpj'), table_name='usuarios', schema='user')
    op.drop_column('usuarios', 'ativada_em', schema='user')
    op.drop_column('usuarios', 'cnpj', schema='user')
    op.drop_index(op.f('ix_user_universidades_cnpj'), table_name='universidades', schema='user')
    op.drop_column('universidades', 'cnpj', schema='user')
    # ### end Alembic commands ###
