"""esquema inicial v2 com vinculo e formacao

Revision ID: ef394f3040de
Revises: 
Create Date: 2026-09-23 20:28:11.847882
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'ef394f3040de'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome_completo', sa.String(length=200), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('tipo', sa.Enum('aluno', 'faculdade', 'empresa', name='tipo_conta', schema='user'), nullable=False),
    sa.Column('foto_url', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.String(length=280), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('alterado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuarios')),
    sa.UniqueConstraint('email', name=op.f('uq_usuarios_email')),
    schema='user'
    )
    op.create_index(op.f('ix_user_usuarios_cpf'), 'usuarios', ['cpf'], unique=True, schema='user')
    op.create_index(op.f('ix_user_usuarios_username'), 'usuarios', ['username'], unique=True, schema='user')
    op.create_index('ix_usuarios_trgm_nome', 'usuarios', ['nome_completo'], unique=False, schema='user', postgresql_using='gin', postgresql_ops={'nome_completo': 'gin_trgm_ops'})
    op.create_index('ix_usuarios_trgm_username', 'usuarios', ['username'], unique=False, schema='user', postgresql_using='gin', postgresql_ops={'username': 'gin_trgm_ops'})
    op.create_table('seguindo_usuarios',
    sa.Column('seguidor_id', sa.UUID(), nullable=False),
    sa.Column('seguido_id', sa.UUID(), nullable=False),
    sa.Column('seguido_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('seguidor_id <> seguido_id', name=op.f('ck_seguindo_usuarios_nao_seguir_a_si_mesmo')),
    sa.ForeignKeyConstraint(['seguido_id'], ['user.usuarios.id'], name=op.f('fk_seguindo_usuarios_seguido_id_usuarios'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seguidor_id'], ['user.usuarios.id'], name=op.f('fk_seguindo_usuarios_seguidor_id_usuarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('seguidor_id', 'seguido_id', name=op.f('pk_seguindo_usuarios')),
    schema='user'
    )
    op.create_index(op.f('ix_user_seguindo_usuarios_seguido_id'), 'seguindo_usuarios', ['seguido_id'], unique=False, schema='user')
    op.create_table('universidades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('sigla', sa.String(length=20), nullable=False),
    sa.Column('bio', sa.String(length=280), nullable=True),
    sa.Column('foto_url', sa.String(length=500), nullable=True),
    sa.Column('conta_id', sa.UUID(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conta_id'], ['user.usuarios.id'], name=op.f('fk_universidades_conta_id_usuarios'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_universidades')),
    sa.UniqueConstraint('conta_id', name=op.f('uq_universidades_conta_id')),
    sa.UniqueConstraint('nome', name=op.f('uq_universidades_nome')),
    schema='user'
    )
    op.create_index(op.f('ix_user_universidades_sigla'), 'universidades', ['sigla'], unique=False, schema='user')
    op.create_table('cursos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('universidade_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['universidade_id'], ['user.universidades.id'], name=op.f('fk_cursos_universidade_id_universidades'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cursos')),
    sa.UniqueConstraint('universidade_id', 'nome', name=op.f('uq_cursos_universidade_id')),
    schema='user'
    )
    op.create_index(op.f('ix_user_cursos_universidade_id'), 'cursos', ['universidade_id'], unique=False, schema='user')
    op.create_table('seguindo_universidades',
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('universidade_id', sa.UUID(), nullable=False),
    sa.Column('seguida_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['universidade_id'], ['user.universidades.id'], name=op.f('fk_seguindo_universidades_universidade_id_universidades'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.usuarios.id'], name=op.f('fk_seguindo_universidades_usuario_id_usuarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id', 'universidade_id', name=op.f('pk_seguindo_universidades')),
    schema='user'
    )
    op.create_table('formacoes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('universidade_id', sa.UUID(), nullable=False),
    sa.Column('curso_id', sa.UUID(), nullable=False),
    sa.Column('verificada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['curso_id'], ['user.cursos.id'], name=op.f('fk_formacoes_curso_id_cursos'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['universidade_id'], ['user.universidades.id'], name=op.f('fk_formacoes_universidade_id_universidades'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.usuarios.id'], name=op.f('fk_formacoes_usuario_id_usuarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_formacoes')),
    sa.UniqueConstraint('usuario_id', 'universidade_id', 'curso_id', name=op.f('uq_formacoes_usuario_id')),
    schema='user'
    )
    op.create_index(op.f('ix_user_formacoes_usuario_id'), 'formacoes', ['usuario_id'], unique=False, schema='user')
    op.create_table('matriculas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('universidade_id', sa.UUID(), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('curso_id', sa.UUID(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("cpf ~ '^[0-9]{11}$'", name=op.f('ck_matriculas_cpf_somente_digitos')),
    sa.ForeignKeyConstraint(['curso_id'], ['user.cursos.id'], name=op.f('fk_matriculas_curso_id_cursos'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['universidade_id'], ['user.universidades.id'], name=op.f('fk_matriculas_universidade_id_universidades'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matriculas')),
    sa.UniqueConstraint('universidade_id', 'cpf', name=op.f('uq_matriculas_universidade_id')),
    schema='user'
    )
    op.create_index(op.f('ix_user_matriculas_cpf'), 'matriculas', ['cpf'], unique=False, schema='user')
    op.create_index(op.f('ix_user_matriculas_universidade_id'), 'matriculas', ['universidade_id'], unique=False, schema='user')
    op.create_table('vinculos',
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('universidade_id', sa.UUID(), nullable=False),
    sa.Column('curso_id', sa.UUID(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['curso_id'], ['user.cursos.id'], name=op.f('fk_vinculos_curso_id_cursos'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['universidade_id'], ['user.universidades.id'], name=op.f('fk_vinculos_universidade_id_universidades'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.usuarios.id'], name=op.f('fk_vinculos_usuario_id_usuarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id', name=op.f('pk_vinculos')),
    schema='user'
    )
    op.create_index(op.f('ix_user_vinculos_universidade_id'), 'vinculos', ['universidade_id'], unique=False, schema='user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_vinculos_universidade_id'), table_name='vinculos', schema='user')
    op.drop_table('vinculos', schema='user')
    op.drop_index(op.f('ix_user_matriculas_universidade_id'), table_name='matriculas', schema='user')
    op.drop_index(op.f('ix_user_matriculas_cpf'), table_name='matriculas', schema='user')
    op.drop_table('matriculas', schema='user')
    op.drop_index(op.f('ix_user_formacoes_usuario_id'), table_name='formacoes', schema='user')
    op.drop_table('formacoes', schema='user')
    op.drop_table('seguindo_universidades', schema='user')
    op.drop_index(op.f('ix_user_cursos_universidade_id'), table_name='cursos', schema='user')
    op.drop_table('cursos', schema='user')
    op.drop_index(op.f('ix_user_universidades_sigla'), table_name='universidades', schema='user')
    op.drop_table('universidades', schema='user')
    op.drop_index(op.f('ix_user_seguindo_usuarios_seguido_id'), table_name='seguindo_usuarios', schema='user')
    op.drop_table('seguindo_usuarios', schema='user')
    op.drop_index('ix_usuarios_trgm_username', table_name='usuarios', schema='user', postgresql_using='gin', postgresql_ops={'username': 'gin_trgm_ops'})
    op.drop_index('ix_usuarios_trgm_nome', table_name='usuarios', schema='user', postgresql_using='gin', postgresql_ops={'nome_completo': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_user_usuarios_username'), table_name='usuarios', schema='user')
    op.drop_index(op.f('ix_user_usuarios_cpf'), table_name='usuarios', schema='user')
    op.drop_table('usuarios', schema='user')
    # ### end Alembic commands ###
