"""esquema inicial: posts, curtidas e comentarios do feed

Revision ID: 4b47eeb9e15b
Revises: 
Create Date: 2026-09-28 19:57:06.217060
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '4b47eeb9e15b'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('autor_id', sa.UUID(), nullable=False),
    sa.Column('autor_tipo', sa.Enum('aluno', 'empresa', name='tipo_de_autor', schema='feed'), nullable=False),
    sa.Column('autor_universidade_id', sa.UUID(), nullable=True),
    sa.Column('conteudo', sa.String(length=2000), nullable=False),
    sa.Column('imagem_url', sa.String(length=500), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('editado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_posts')),
    schema='feed'
    )
    op.create_index('ix_posts_autor_criado_em', 'posts', ['autor_id', 'criado_em'], unique=False, schema='feed')
    op.create_index('ix_posts_universidade_criado_em', 'posts', ['autor_universidade_id', 'criado_em'], unique=False, schema='feed')
    op.create_table('comentarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('autor_id', sa.UUID(), nullable=False),
    sa.Column('conteudo', sa.String(length=1000), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['feed.posts.id'], name=op.f('fk_comentarios_post_id_posts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comentarios')),
    schema='feed'
    )
    op.create_index('ix_comentarios_post_criado_em', 'comentarios', ['post_id', 'criado_em'], unique=False, schema='feed')
    op.create_index(op.f('ix_feed_comentarios_autor_id'), 'comentarios', ['autor_id'], unique=False, schema='feed')
    op.create_table('curtidas',
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['feed.posts.id'], name=op.f('fk_curtidas_post_id_posts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'usuario_id', name=op.f('pk_curtidas')),
    schema='feed'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('curtidas', schema='feed')
    op.drop_index(op.f('ix_feed_comentarios_autor_id'), table_name='comentarios', schema='feed')
    op.drop_index('ix_comentarios_post_criado_em', table_name='comentarios', schema='feed')
    op.drop_table('comentarios', schema='feed')
    op.drop_index('ix_posts_universidade_criado_em', table_name='posts', schema='feed')
    op.drop_index('ix_posts_autor_criado_em', table_name='posts', schema='feed')
    op.drop_table('posts', schema='feed')
    # ### end Alembic commands ###
